# Generated by Django 2.1.7 on 2019-03-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190312_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('albuquerque', 'ALBUQUERQUE'), ('anchorage', 'ANCHORAGE'), ('asheville', 'ASHEVILLE'), ('atlanta', 'ATLANTA'), ('austin', 'AUSTIN'), ('baltimore', 'BALTIMORE'), ('birmingham_al', 'BIRMINGHAM_AL'), ('boise', 'BOISE')], default='ALBUQUERQUE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
