# Generated by Django 2.1.7 on 2019-03-14 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190314_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='buddy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.DecimalField(decimal_places=5, default=5, max_digits=7),
            preserve_default=False,
        ),
    ]
