# Generated by Django 2.1.7 on 2019-03-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190314_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('Albuquerque', 'Albuquerque'), ('Anchorage', 'Anchorage'), ('Asheville', 'Asheville'), ('Atlanta', 'Atlanta'), ('Austin', 'Austin'), ('Baltimore', 'Baltimore'), ('Birmingham, AL', 'Birmingham, AL'), ('Boise', 'Boise')], default='ALBUQUERQUE', max_length=100, null=True),
        ),
    ]
