# Generated by Django 2.1.7 on 2019-03-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190322_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('Albuquerque', 'Albuquerque'), ('Anchorage', 'Anchorage'), ('Asheville', 'Asheville'), ('Atlanta', 'Atlanta'), ('Austin', 'Austin'), ('Baltimore', 'Baltimore'), ('Birmingham, AL', 'Birmingham-AL'), ('Boise', 'Boise'), ('Boston', 'Boston'), ('Boulder', 'Boulder'), ('Buffalo', 'Buffalo'), ('Charleston', 'Charleston'), ('Charlotte', 'Charlotte'), ('Chattanooga', 'Chattanooga'), ('Chicago', 'Chicago'), ('Cincinnati', 'Cincinnati'), ('Cleveland', 'Cleveland'), ('Colorado Springs', 'Colorado-Springs'), ('Columbus', 'Columbus'), ('Dallas', 'Dallas'), ('Denver', 'Denver'), ('Des Moines', 'Des-Moines'), ('Detroit', 'Detroit'), ('Eugene', 'Eugene'), ('Fort Collins', 'Fort-Collins'), ('Honolulu', 'Honolulu'), ('Houston', 'Houston'), ('Indianapolis', 'Indianapolis'), ('Jacksonville', 'Jacksonville'), ('Kansas City', 'Kansas City'), ('Knoxville', 'Knoxville'), ('Las Vegas', 'Las-Vegas'), ('Los Angeles', 'Los-Angeles'), ('Louisville', 'Louisville'), ('Madison', 'Madison'), ('Memphis', 'Memphis'), ('Miami', 'Miami'), ('Milwaukee', 'Milwaukee'), ('Minneapolis-Saint Paul', 'Minneapolis-Saint-Paul'), ('Nashville', 'Nashville'), ('New Orleans', 'New-Orleans'), ('New York', 'New York'), ('Oklahoma City', 'Oklahoma-City'), ('Omaha', 'Omaha'), ('Orlando', 'Orlando'), ('Palo Alto', 'Palo-Alto'), ('Philadelphia', 'Philadelphia'), ('Phoenix', 'Phoenix'), ('Pittsburgh', 'Pittsburgh'), ('Portland, ME', 'Portland-ME'), ('Portland, OR', 'Portland-OR'), ('Providence', 'Providence'), ('Raleigh', 'Raleigh'), ('Richmond', 'Richmond'), ('Rochester', 'Rochester'), ('Salt Lake City', 'Salt-Lake-City'), ('San Antonio', 'San-Antonio'), ('San Diego', 'San-Diego'), ('San Francisco Bay Area', 'San-Francisco-Bay-Area'), ('Seattle', 'Seatte'), ('St. Louis', 'St-Louis'), ('Tampa Bay Area', 'Tampa-Bay-Area'), ('Washington, D.C.', 'Washington-DC')], default='ALBUQUERQUE', max_length=100, null=True),
        ),
    ]
