# Generated by Django 2.1.7 on 2019-03-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190328_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('Albuquerque', 'Albuquerque'), ('Anchorage', 'Anchorage'), ('Asheville', 'Asheville'), ('Atlanta', 'Atlanta'), ('Austin', 'Austin'), ('Baltimore', 'Baltimore'), ('Boise', 'Boise'), ('Boston', 'Boston'), ('Boulder', 'Boulder'), ('Buffalo', 'Buffalo'), ('Charleston', 'Charleston'), ('Charlotte', 'Charlotte'), ('Chattanooga', 'Chattanooga'), ('Chicago', 'Chicago'), ('Cincinnati', 'Cincinnati'), ('Cleveland', 'Cleveland'), ('Columbus', 'Columbus'), ('Dallas', 'Dallas'), ('Denver', 'Denver'), ('Detroit', 'Detroit'), ('Eugene', 'Eugene'), ('Honolulu', 'Honolulu'), ('Houston', 'Houston'), ('Indianapolis', 'Indianapolis'), ('Jacksonville', 'Jacksonville'), ('Kansas City', 'Kansas City'), ('Knoxville', 'Knoxville'), ('Louisville', 'Louisville'), ('Madison', 'Madison'), ('Memphis', 'Memphis'), ('Miami', 'Miami'), ('Milwaukee', 'Milwaukee'), ('Nashville', 'Nashville'), ('Omaha', 'Omaha'), ('Orlando', 'Orlando'), ('Philadelphia', 'Philadelphia'), ('Phoenix', 'Phoenix'), ('Pittsburgh', 'Pittsburgh'), ('Providence', 'Providence'), ('Raleigh', 'Raleigh'), ('Richmond', 'Richmond'), ('Rochester', 'Rochester'), ('Seattle', 'Seatte')], default='ALBUQUERQUE', max_length=100, null=True),
        ),
    ]
