# Generated by Django 2.1.7 on 2019-03-19 18:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
